language: python

python:
  - "3.7"

# command to install dependencies
install:
  - make dependences

services:
  - postgresql
    
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
 
# command to run tests
script: 
  - make start
  - make status
  - make -B test
 

after_success:
  - make stop
  - make delete

  - cd ./test 
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
  - coveralls


