language: python

python:
  - "3.6.6"

# command to install dependencies
install:
  - pip3 install -r requirements.txt

services:
  - postgresql
    
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
 
# command to run tests
script: cd ./test && pytest -v test.py 
